sudo: required
services:
  - docker

before_install:
  - docker build -t crmessin/docker-react -f Dockerfile.dev .
##Using -e to exit when done
script:
  - docker run -e CI=true crmessin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-787755735440"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure:"$AWS_SECRET_KEY"